### PR TITLE
Added functionality for RemoteAccessVPN and RemoteAccessVpnUser management

### PR DESCRIPTION
**Pull request by swill**
Implementation for the following two interfaces to support the the management of both RemoteAccessVpns and RemoteAccessVpnUsers.

```
type RemoteAccessVpnService interface {
	Get(id string) (*RemoteAccessVpn, error)
	List() ([]RemoteAccessVpn, error)
	ListWithOptions(options map[string]string) ([]RemoteAccessVpn, error)
	Enable(id string) (bool, error)
	Disable(id string) (bool, error)
}
```

```
type RemoteAccessVpnUserService interface {
	Get(id string) (*RemoteAccessVpnUser, error)
	List() ([]RemoteAccessVpnUser, error)
	Create(remoteAccessVpnUser RemoteAccessVpnUser) (bool, error)
	Delete(remoteAccessVpnUser RemoteAccessVpnUser) (bool, error)
}
```

The implementation includes the appropriate test coverage.

The implementation has been tested via a script to exercise the different API calls and I have confirmed that the implementation works for both the `L2TP` and `IKEV2` implementations.

**Note:**
While this implementation works as defined, there are a couple elements which are non-standard.

You will notice that the signature for `Create(remoteAccessVpnUser RemoteAccessVpnUser) (bool, error)` does not return an object for the created entity.  This is due to the following issue: https://cloud-ops.atlassian.net/browse/MC-8774

You will also notice that the signature for `Delete(remoteAccessVpnUser RemoteAccessVpnUser) (bool, error)` does not take the standard `id string` argument which is standard for a `Delete` operations.  This is due to the following issue: https://cloud-ops.atlassian.net/browse/MC-8773

It is expected that when these issues are resolved the signature for these two function calls will change to reflect the expected behavior.

### CODE REVIEW

**Review by pdube — APPROVED** [review]
Great first PR. LGTM 👍 You can ignore the cicleCI error. The config hasn't been pushed yet

**Review by khos2ow — APPROVED** [review]
LGTM

**Comment by swill** [comment]
Anything else I need to do with this?  Do I need to somehow update the version and such of the client?

I need these changes in the terraform plugin (which I am currently modifying), so I will have to add these changes via the `vendor` folder in the plugin as well.  Thoughts?  What is the process here?

**Comment by khos2ow** [comment]
No, it should be good now. What needs to be done is that this PR gets merged and a new Release is created from HEAD of master (`v1.4.0` should be a good candidate). Then in the plugin update the [go.mod](https://github.com/cloud-ca/terraform-provider-cloudca/blob/master/go.mod#L6) to pin the `go-cloudca` version to corresponding version and `make vendor` to update the dependency.

**Comment by swill** [comment]
Thanks @khos2ow.  I will wait for this to get merged and a release cut and then I will update the terraform plugin with my changes.

**Comment by pdube** [comment]
@swill Is everything looking good on this? If so, there are 2 approvals, so we could merge this

**Comment by swill** [comment]
I have confirmed everything here is working as expected (as it pertains to developing the terraform plugin).  I will update the docs for the terraform plugin and push that PR later today.

This one is ready to merge from my perspective.  Thanks...

**Pull request merged**
